name: Publish Extension

on:
  push:
    branches:
      - main
      - publish_extn

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19.x
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm run install:all

      - name: Install webview dependencies
        run: npm run build:webview
      - name: Bundle
        run: npm run webpack

      - name: Install vscode extensions
        run: npm install -g @vscode/vsce

      - name: Publish extension
        run: vsce publish --allow-missing-repository -p ${{ secrets.PUBLISHER_TOKEN }} --no-git-tag-version 0.0.${{ github.run_number }}
